# This is a basic workflow to help you get started with Actions

name: Create Web App

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Backend
      uses: actions/checkout@v2
      with:
        ref: develop
        path: backend
    
    - name: Checkout Frontend
      uses: actions/checkout@v2
      with:
        repository: nagyDarius/inspectorgit-frontend
        path: frontend
        ref: develop
        token: ${{ secrets.GIT_API_TOKEN }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Runs a set of commands using the runners shell
    - name: Build Frontend
      run:
        mvn -f frontend/pom.xml clean install
        
    - name: Build Backend
      run: 
        mvn -f backend/pom.xml clean install -DskipTests
        
    - name: Upload Jar as artifact
      uses: actions/upload-artifact@v1
      with:
        name: inspector-git-web-app
        path: backend/app/target/app-1.0-SNAPSHOT.jar
        
        
        
